# Generated by Django 3.2.6 on 2021-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210829_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Employee', 'Employee')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='PartOf',
        ),
    ]
