# Generated by Django 3.2.6 on 2021-09-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
