# Generated by Django 3.2.6 on 2021-09-01 14:37

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_task_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True, validators=[employee.models.validate_due_date]),
        ),
    ]
