# Generated by Django 3.2.6 on 2021-09-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_task_asignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='asignee',
            new_name='assignee',
        ),
    ]
