# Generated by Django 3.2.8 on 2021-10-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user-profile-default.png', null=True, upload_to='profile_pictures'),
        ),
    ]
