# Generated by Django 3.2.8 on 2021-10-30 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_employeeprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_picture',
            field=models.ImageField(default='user-profile-default.png', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
